### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by DeepSeaCatz** [Haoming02/comfyui-prompt-format#4]
Hi, I've tried to use the Format button on various string nodes, but it doesn't seem to do anything.

I get this error when pressing it:
![image](https://github.com/user-attachments/assets/5ab857da-a4f8-49c0-8b80-d6d99d110def)

Is it suppose to be on a specific node to format the prompt?

Also, I had a suggestion to create a node that auto format prompts instead of having a button. I'm currently creating a workflow that automatically translate the prompt from another language with Google Translator by using [NX_Translator](https://github.com/Franck-Demongin/NX_Translator) node.

Currently it often removes commas `,` and doesn't format the prompt well for Generation. Your tool could be modified into a node and could be added after text nodes to make sure the formatting is well done before it continue. Kind of like a quality control for AI prompting.

![image](https://github.com/user-attachments/assets/fa6c64ea-e25c-4466-8851-3e054cfccece)

**Comment by Haoming02** [comment]
1. As mentioned in the [README](https://github.com/Haoming02/comfyui-prompt-format?tab=readme-ov-file#configs), you need to manually edit the configs to support other nodes. Otherwise, it will only format the default built-in `CLIPTextEncode` node. 
2. The error doesn't seem to be related to this Extension.
3. The purpose of the formatting is for human readability. The extra spaces and commas make basically no difference when passed into `TextEncoder`, afaik anyway. So creating a Node to format the text when the users won't see them feels rather pointless.
